spring.application.name=mvtsbackend
# 1. Conexi\u00f3n a la nube
spring.data.mongodb.uri=mongodb+srv://admin_mvts:IAbaNglCjaN8TkWN@mvts-db.fd6htkp.mongodb.net/mvtsdb?appName=mvts-db
spring.data.mongodb.database=mvtsdb

# 2. Conexi\u00f3n a RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 3. Servidor
server.port=8080