spring.application.name=mvtsbackend
# 1. Conexi\u00f3n a la nube
spring.data.mongodb.uri=mongodb+srv://admin_mvts:IAbaNglCjaN8TkWN@mvts-db.fd6htkp.mongodb.net/mvtsdb?appName=mvts-db
spring.data.mongodb.database=mvtsdb

# 2. Conexi\u00f3n a RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 3. Servidor
server.port=8080

# 4. --- MYSQL (Nueva: Para sem\u00e1foros y reportes) ---
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/mvts_gerencial?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#5. Configuraci\u00f3n de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true